-- Sample/demo events (idempotent — inserts only when the events table is empty,
-- so re-running never duplicates rows)
do $$
begin
  if exists (select 1 from events limit 1) then
    raise notice 'events table not empty - skipping seed';
    return;
  end if;

insert into events (title, institution, event_type, start_date, end_date, start_time, end_time, venue, suburb, description, image_url, event_url, ticket_url, is_free, tags) values

('Archibald Prize 2026', 'Art Gallery of NSW', 'exhibition', '2026-06-05', '2026-08-30', null, null, 'Art Gallery of New South Wales', 'The Domain', 'Australia''s most celebrated and controversial portrait prize returns for 2026. This year''s Archibald Prize showcases works by leading Australian artists competing for the coveted prize. Explore portraits of notable Australians spanning politics, sport, the arts and beyond.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80', 'https://www.artgallery.nsw.gov.au', null, true, array['portrait','painting','Australian art','prize']),

('Wynne & Sulman Prizes 2026', 'Art Gallery of NSW', 'exhibition', '2026-06-05', '2026-08-30', null, null, 'Art Gallery of New South Wales', 'The Domain', 'Shown alongside the Archibald, the Wynne Prize celebrates the best landscape painting of Australian scenery, and the Sulman Prize showcases subject, genre, or mural painting.', 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80', 'https://www.artgallery.nsw.gov.au', null, true, array['landscape','painting','prize']),

('Collected: Highlights from the MCA Collection', 'Museum of Contemporary Art', 'exhibition', '2026-06-01', '2026-09-27', null, null, 'MCA Australia', 'Circular Quay', 'A sweeping survey drawn from over 4,000 works in the MCA Collection, Collected presents contemporary art from Australia and the world. From painting to sculpture, video to performance, this exhibition charts the breadth and depth of contemporary practice.', 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80', 'https://www.mca.com.au', null, true, array['contemporary art','collection','survey']),

('First Nations Voices: Country, Kin and Dreaming', 'Museum of Contemporary Art', 'exhibition', '2026-07-10', '2026-10-11', null, null, 'MCA Australia', 'Circular Quay', 'A major group exhibition celebrating First Nations artistic practice across generations. Works by artists from across Australia explore the connections between Country, community and Dreaming through painting, weaving, sculpture and new media.', 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80', 'https://www.mca.com.au', null, true, array['First Nations','Indigenous','contemporary art']),

('Design and the Future: Powerhouse Collection Reimagined', 'Powerhouse Museum', 'exhibition', '2026-06-15', '2026-11-29', null, null, 'Powerhouse Museum', 'Ultimo', 'How do designers shape the world we live in? This landmark exhibition draws on the Powerhouse''s extraordinary collection of over 500,000 objects to explore design thinking from the Industrial Revolution to the age of AI.', 'https://images.unsplash.com/photo-1581922819941-6ab31ab79afc?w=800&q=80', 'https://www.maas.museum', 'https://www.maas.museum/tickets', false, array['design','technology','innovation','collection']),

('Space Odyssey: Exploring the Universe', 'Powerhouse Museum', 'exhibition', '2026-06-20', '2026-12-20', null, null, 'Powerhouse Museum', 'Ultimo', 'Journey through our solar system and beyond in this immersive family-friendly exhibition. Featuring actual NASA artefacts, interactive simulations, and stories of Australian contributions to space exploration.', 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80', 'https://www.maas.museum', 'https://www.maas.museum/tickets', false, array['space','science','family','NASA']),

('Tall Ships and Traded Goods: Maritime Sydney 1788–1900', 'Australian National Maritime Museum', 'exhibition', '2026-06-01', '2026-08-31', null, null, 'Australian National Maritime Museum', 'Darling Harbour', 'Explore Sydney''s transformation from a penal outpost to a thriving port city. This exhibition traces the maritime trade routes that shaped colonial Australia through maps, ships'' logs, cargo manifests, and stunning artefacts.', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=80', 'https://www.sea.museum', null, false, array['maritime','history','colonial','Sydney']),

('Open Weekend: Climb the HMAS Vampire', 'Australian National Maritime Museum', 'open_day', '2026-06-28', '2026-06-29', '10:00', '16:00', 'Australian National Maritime Museum', 'Darling Harbour', 'Go behind the scenes aboard HMAS Vampire, Australia''s largest warship on public display. Museum staff guide visitors through rarely seen areas of the destroyer during this special open weekend.', 'https://images.unsplash.com/photo-1539664030485-a936c7d29c6e?w=800&q=80', 'https://www.sea.museum', null, false, array['navy','warship','open day','family']),

('The Photography of Max Dupain: Sydney in Focus', 'State Library of NSW', 'exhibition', '2026-06-08', '2026-09-06', null, null, 'State Library of NSW', 'Sydney CBD', 'Drawn entirely from the State Library''s remarkable Max Dupain archive, this free exhibition showcases 80 photographs that defined mid-20th century Australian visual culture — from iconic beach scenes to industrial Sydney.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', 'https://www.sl.nsw.gov.au', null, true, array['photography','archive','Sydney history','Max Dupain']),

('Author Talk: Richard Flanagan in Conversation', 'State Library of NSW', 'talk', '2026-07-14', null, '18:30', '20:00', 'State Library of NSW — Metcalfe Auditorium', 'Sydney CBD', 'Booker Prize winner Richard Flanagan discusses his new novel with Sydney Morning Herald literary editor Susan Wyndham. A rare opportunity to hear one of Australia''s greatest living writers speak candidly about craft, history and the Australian imagination.', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80', 'https://www.sl.nsw.gov.au', 'https://www.sl.nsw.gov.au/events', false, array['author talk','literature','Booker Prize']),

('White Rabbit Collection: New Acquisitions 2026', 'White Rabbit Gallery', 'exhibition', '2026-07-01', '2026-10-04', null, null, 'White Rabbit Gallery', 'Chippendale', 'The latest presentation of Judith Neilson''s world-renowned collection of 21st-century Chinese contemporary art. This season brings together new acquisitions alongside iconic works, exploring themes of memory, migration and modernity.', 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80', 'https://www.whiterabbitcollection.org', null, true, array['Chinese art','contemporary','collection']),

('Hyde Park Barracks: Convict Lives', 'Sydney Living Museums', 'heritage', '2026-06-01', '2026-08-31', null, null, 'Hyde Park Barracks', 'Sydney CBD', 'Step inside one of Australia''s most significant World Heritage-listed convict sites. Discover the stories of the 50,000 men and boys who were incarcerated here between 1819 and 1848 through immersive displays, artefacts and first-person accounts.', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', 'https://www.sydneylivingmuseums.com.au', 'https://www.sydneylivingmuseums.com.au/tickets', false, array['convict','World Heritage','colonial history','UNESCO']),

('Elizabeth Farm: Harvest Day', 'Sydney Living Museums', 'open_day', '2026-06-21', null, '10:00', '15:00', 'Elizabeth Farm', 'Rosehill', 'Celebrate mid-winter at Australia''s oldest surviving European building. Join costumed interpreters for harvest demonstrations, colonial cooking, basket weaving and guided tours of the historic farmhouse and gardens.', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', 'https://www.sydneylivingmuseums.com.au', null, false, array['heritage','colonial','family','history']),

('Sydney Festival: Opening Night Gala', 'Sydney Festival', 'festival', '2026-07-03', null, '19:00', '23:00', 'Hyde Park', 'Sydney CBD', 'Sydney Festival kicks off with a spectacular free opening night in Hyde Park. Expect live performances, light installations, food and celebration from artists across Australia and the world.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80', 'https://www.sydneyfestival.org.au', null, true, array['festival','free','outdoor','music','performance']),

('Sydney Festival: Bangarra Dance Theatre — Wiradjuri', 'Sydney Festival', 'performance', '2026-07-08', '2026-07-19', '19:30', '21:00', 'Sydney Opera House — Drama Theatre', 'Circular Quay', 'Bangarra Dance Theatre returns to Sydney Festival with Wiradjuri, a new work exploring the culture and Country of the Wiradjuri people — the largest Aboriginal nation in NSW. A powerful fusion of contemporary dance and traditional movement.', 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&q=80', 'https://www.sydneyfestival.org.au', 'https://www.sydneyfestival.org.au/tickets', false, array['dance','Bangarra','First Nations','Sydney Opera House']),

('Sydney Festival: The Book of Clarice — World Premiere', 'Sydney Festival', 'performance', '2026-07-10', '2026-07-26', '20:00', '21:45', 'Roslyn Packer Theatre', 'Walsh Bay', 'A world-premiere theatrical adaptation of Clarice Lispector''s collected letters, co-produced with Teatro Municipal do Rio de Janeiro. A meditation on writing, desire, exile and Brazilian modernism.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', 'https://www.sydneyfestival.org.au', 'https://www.sydneyfestival.org.au/tickets', false, array['theatre','world premiere','Brazil','literature']),

('Sydney Festival: Parramatta Lanes', 'Sydney Festival', 'festival', '2026-07-17', '2026-07-20', '17:00', '23:00', 'Church Street Laneways', 'Parramatta', 'Western Sydney''s beloved laneway festival returns for four nights of music, street food, art installations and cultural performance. Free entry, family friendly until 9pm.', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80', 'https://www.sydneyfestival.org.au', null, true, array['street food','music','Parramatta','laneway','family']),

('Vivid Sydney: Lighting of the Sails (Late Season)', 'Vivid Sydney', 'festival', '2026-06-01', '2026-06-08', '18:00', '23:00', 'Sydney Opera House', 'Circular Quay', 'The final days of Vivid Sydney''s light spectacular on the sails of the Opera House. A different projection every evening celebrating Pacific art and culture, visible from Circular Quay and the Harbour Bridge walk.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', 'https://www.vividsydney.com', null, true, array['Vivid','lights','Opera House','outdoor','family']),

('Sydney Writers'' Festival: The Climate Emergency', 'Sydney Writers'' Festival', 'talk', '2026-06-02', null, '13:00', '14:30', 'Carriageworks', 'Eveleigh', 'Four leading writers — including a Pulitzer Prize finalist — discuss how fiction and non-fiction are rising to meet the challenge of the climate crisis. Chaired by ABC''s science editor.', 'https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=800&q=80', 'https://www.swf.org.au', 'https://www.swf.org.au/tickets', false, array['climate','literature','panel','Carriageworks']),

('Sydney Writers'' Festival: Free Community Day', 'Sydney Writers'' Festival', 'festival', '2026-06-07', null, '10:00', '18:00', 'Carriageworks', 'Eveleigh', 'The final free day of Sydney Writers'' Festival brings together authors, poets, storytellers and spoken word artists for a packed program accessible to everyone. Kids'' sessions, readings, signings and more.', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&q=80', 'https://www.swf.org.au', null, true, array['free','family','books','festival','Carriageworks']),

('Biennale of Sydney: Ten Thousand Suns', 'Biennale of Sydney', 'exhibition', '2026-06-01', '2026-07-13', null, null, 'Cockatoo Island + Multiple Venues', 'Cockatoo Island', 'The 24th Biennale of Sydney unfolds across Cockatoo Island, Carriageworks and the MCA. This year''s edition — Ten Thousand Suns — gathers 80 artists from 40 countries to explore energy, ecology and transformation.', 'https://images.unsplash.com/photo-1531685250784-7569952593d2?w=800&q=80', 'https://www.biennaleofsydney.art', null, true, array['biennale','international art','Cockatoo Island','ecology']),

('Biennale of Sydney: Artist Talk — Kara Walker', 'Biennale of Sydney', 'talk', '2026-06-18', null, '18:00', '19:30', 'MCA Auditorium', 'Circular Quay', 'American artist Kara Walker discusses her monumental new commission for the Biennale with curator Cosmin Costinas. Walker''s work confronts histories of racial violence through her trademark silhouette technique.', 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80', 'https://www.biennaleofsydney.art', 'https://www.biennaleofsydney.art/events', false, array['artist talk','Kara Walker','Biennale','MCA']),

('City of Sydney: Winter Village — Ice Skating in the Park', 'City of Sydney', 'festival', '2026-06-20', '2026-08-10', '10:00', '21:00', 'Hyde Park South', 'Sydney CBD', 'The beloved Winter Village returns to Hyde Park with an outdoor ice rink, alpine food stalls, mulled wine, fire pits and live entertainment every weekend. Sydney''s favourite winter gathering for families and friends.', 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80', 'https://www.cityofsydney.nsw.gov.au', 'https://www.cityofsydney.nsw.gov.au/events', false, array['winter','ice skating','family','outdoor','Hyde Park']),

('City of Sydney: Open Studio Trail — Redfern/Waterloo', 'City of Sydney', 'open_day', '2026-07-26', '2026-07-27', '10:00', '17:00', 'Various Artist Studios', 'Redfern', 'Over 40 artists open their studio doors across Redfern and Waterloo for this free self-guided trail. Meet painters, sculptors, ceramicists, textile artists and printmakers working in one of Sydney''s most creative precincts.', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80', 'https://www.cityofsydney.nsw.gov.au', null, true, array['open studio','Redfern','artists','self-guided']),

('Inner West Council: Newtown Festival Winter Edition', 'Inner West Council', 'festival', '2026-07-05', null, '11:00', '19:00', 'Camperdown Memorial Rest Park', 'Newtown', 'The Newtown Festival''s winter edition fills Camperdown park with live music across three stages, local market stalls, community art projects, food trucks and spoken word. Free entry, all ages welcome.', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80', 'https://www.innerwest.nsw.gov.au', null, true, array['Newtown','music','market','outdoor','community']),

('Inner West Council: Marrickville Open Studios', 'Inner West Council', 'open_day', '2026-08-08', '2026-08-09', '10:00', '17:00', 'Various locations', 'Marrickville', 'Explore the thriving creative community of Marrickville through this annual open studio event. Over 60 participating artists across industrial studios, converted warehouses and home workshops.', 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80', 'https://www.innerwest.nsw.gov.au', null, true, array['open studio','Marrickville','artists','Inner West']),

('AGNSW: Art After Hours — Winter Series', 'Art Gallery of NSW', 'other', '2026-06-11', '2026-08-27', '17:00', '21:00', 'Art Gallery of New South Wales', 'The Domain', 'The Gallery opens late every Wednesday evening for Art After Hours. Free entry after 5pm to all permanent collection galleries and special exhibitions, complemented by talks, tours, music and a licensed bar.', 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&q=80', 'https://www.artgallery.nsw.gov.au', null, true, array['free','evening','social','drinks','art']),

('Powerhouse: Design Futures Summit', 'Powerhouse Museum', 'talk', '2026-08-13', '2026-08-14', '09:00', '17:00', 'Powerhouse Museum', 'Ultimo', 'A two-day symposium bringing together designers, technologists, ecologists and policymakers to imagine sustainable futures for Australian cities. Speakers from Australia, Japan, the Netherlands and Brazil.', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', 'https://www.maas.museum', 'https://www.maas.museum/events', false, array['design','summit','sustainability','conference']),

('MCA: Zines & Self-Publishing Workshop', 'Museum of Contemporary Art', 'other', '2026-07-19', null, '13:00', '16:00', 'MCA Australia — Level 3 Learning Space', 'Circular Quay', 'Learn to create your own zine in this hands-on afternoon workshop led by Perks and Mini (P.A.M.) co-founder Misha Hollenbach. Materials provided. Suitable for ages 16+. Bookings essential.', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80', 'https://www.mca.com.au', 'https://www.mca.com.au/events', false, array['workshop','zines','printmaking','self-publishing']),

('State Library: Rare Books Open Day', 'State Library of NSW', 'open_day', '2026-08-22', null, '10:00', '16:00', 'State Library of NSW — Mitchell Library', 'Sydney CBD', 'The Mitchell Library opens its treasures for public inspection — illuminated manuscripts, first editions of Australian literature, original maps, and documents relating to European contact with the Pacific. Guided tours on the hour.', 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80', 'https://www.sl.nsw.gov.au', null, true, array['rare books','manuscripts','Mitchell Library','history']),

('White Rabbit Gallery: Artist-Led Tour', 'White Rabbit Gallery', 'talk', '2026-08-01', null, '14:00', '15:30', 'White Rabbit Gallery', 'Chippendale', 'Join Chinese-Australian artist and White Rabbit Collection collaborator Liu Xiaodong on a personal tour of the new season. Liu shares his insights into the artists featured and the cultural contexts shaping their work.', 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=800&q=80', 'https://www.whiterabbitcollection.org', 'https://www.whiterabbitcollection.org/events', false, array['guided tour','Chinese art','artist talk','Chippendale']),

('Sydney Festival: Neon Reef — Immersive Light Installation', 'Sydney Festival', 'festival', '2026-07-03', '2026-07-27', '18:00', '23:00', 'Darling Harbour', 'Darling Harbour', 'Plunge beneath the surface in this spectacular free outdoor installation transforming Darling Harbour into a bioluminescent reef. A collaboration between Sydney-based designer Brigid Costello and marine biologists from the University of Sydney.', 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80', 'https://www.sydneyfestival.org.au', null, true, array['light installation','Darling Harbour','free','outdoor','ocean']),

('AGNSW: Architecture of Empire — Photography Exhibition', 'Art Gallery of NSW', 'exhibition', '2026-08-01', '2026-11-08', null, null, 'Art Gallery of New South Wales — Brett Whiteley Studio', 'Surry Hills', 'An expansive photographic survey of British colonial architecture across South Asia, Africa and the Pacific. Through 200 photographs spanning 1860–1970, this exhibition interrogates the visual grammar of empire and its contested legacies.', 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80', 'https://www.artgallery.nsw.gov.au', null, true, array['photography','architecture','colonial history','Surry Hills']);
end $$;
